In [1]:
import pandas as pd
import os

In [2]:
RAW_DATA_PATH = "../data/raw"
PROCESSED_DATA_PATH = "../data/processed"

os.makedirs(PROCESSED_DATA_PATH, exist_ok=True)

In [3]:
cleaning_summary = []

for file in os.listdir(RAW_DATA_PATH):

    if file.endswith(".csv"):

        stock_name = file.replace(".csv", "")

        print(f"Cleaning {stock_name}...")

        # Load data
        df = pd.read_csv(
            os.path.join(RAW_DATA_PATH, file)
        )

        # Convert Date to datetime
        df["Date"] = pd.to_datetime(df["Date"])

        # Sort by date
        df = df.sort_values("Date")

        # Remove duplicates
        duplicates_before = df.duplicated().sum()
        df = df.drop_duplicates()

        # Remove rows with invalid prices
        df = df[
            (df["Open"] > 0) &
            (df["High"] > 0) &
            (df["Low"] > 0) &
            (df["Close"] > 0)
        ]

        # Add stock name
        df["Stock"] = stock_name

        # Reset index
        df = df.reset_index(drop=True)

        # Save processed dataset
        output_path = os.path.join(
            PROCESSED_DATA_PATH,
            file
        )

        df.to_csv(
            output_path,
            index=False
        )

        cleaning_summary.append({
            "Stock": stock_name,
            "Rows": len(df),
            "Duplicates Removed": duplicates_before,
            "Missing Values": df.isnull().sum().sum()
        })

        print(f"✓ Saved cleaned {stock_name}")

summary_df = pd.DataFrame(cleaning_summary)

summary_df

Cleaning AXISBANK...
✓ Saved cleaned AXISBANK
Cleaning BHARTIARTL...
✓ Saved cleaned BHARTIARTL
Cleaning HDFCBANK...
✓ Saved cleaned HDFCBANK
Cleaning ICICIBANK...
✓ Saved cleaned ICICIBANK
Cleaning INFY...
✓ Saved cleaned INFY
Cleaning ITC...
✓ Saved cleaned ITC
Cleaning LT...
✓ Saved cleaned LT
Cleaning RELIANCE...
✓ Saved cleaned RELIANCE
Cleaning SBIN...
✓ Saved cleaned SBIN
Cleaning TCS...
✓ Saved cleaned TCS

        Stock  Rows  Duplicates Removed  Missing Values
0    AXISBANK  2878                   0               0
1  BHARTIARTL  2878                   0               0
2    HDFCBANK  2878                   0               0
3   ICICIBANK  2878                   0               0
4        INFY  2878                   0               0
5         ITC  2878                   0               0
6          LT  2878                   0               0
7    RELIANCE  2878                   0               0
8        SBIN  2878                   0               0
9         TCS  2878                   0               0

In [4]:
df = pd.read_csv("../data/processed/SBIN.csv")
df.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Stock
0,2015-01-01,274.924988,314.000000,315.000000,310.700012,312.450012,6138488,SBIN
1,2015-01-02,276.019440,315.250000,318.299988,314.350006,314.350006,9935094,SBIN
2,2015-01-05,273.830566,312.750000,316.799988,312.100006,316.250000,9136716,SBIN
3,2015-01-06,262.579651,299.899994,311.100006,298.700012,310.000000,15329257,SBIN
4,2015-01-07,262.798492,300.149994,302.549988,295.149994,300.000000,15046745,SBIN